In [1]:
import numpy as np
a = np.array([10,20,30,40])
print(a)
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(a.size)
print(a.dtype)
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
data = np.array([10,20,30,40,50])
print(np.mean(data))
print(np.median(data))
print(np.max(data))
print(np.min(data))
print(np.sum(data))


[10 20 30 40]
[[1 2 3]
 [4 5 6]]
4
int32
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
30.0
30.0
50
10
150
